BASE_KEYWORDS = [
    "ai for security",
    "security of ai",
    "adversarial",
    "anomaly detection",
    "alignment",
    "attack",
    "auditor",
    "backdoor",
    "constitutional",
    "content safety",
    "cybersecurity",
    "data poisoning",
    "defense",
    "detection",
    "harmful",
    "hallucination",
    "inference attack",
    "interpretability",
    "intrusion detection",
    "jailbreak",
    "llm security",
    "malicious",
    "malware",
    "membership inference",
    "moderation",
    "network intrusion",
    "phishing",
    "poison",
    "privacy",
    "private inference",
    "prompt injection",
    "red team",
    "robust",
    "robustness",
    "safe ai",
    "safety",
    "secure",
    "security",
    "steering",
    "threat",
    "toxic",
    "trojan",
    "unlearn",
    "vulnerability",
    "vulnerability detection",
    "watermark",
]
