MARKDOWN_SOURCE_URL = "https://raw.githubusercontent.com/Zhou-Zi7/AI-Security-Resources/main/README.md"


SOURCE_DEFINITIONS = [
    {
        "source_id": "sp",
        "name": "S&P",
        "category": "顶级安全会议",
        "description": "BIG4 AI 安全论文聚合仓库中的 IEEE S&P 分区。",
        "url": "https://github.com/Zhou-Zi7/Awesome-AI-Security-BIG4",
        "fetcher": "big4_markdown",
        "extra": {"heading": "## Papers in S&P"},
    },
    {
        "source_id": "ndss",
        "name": "NDSS",
        "category": "顶级安全会议",
        "description": "BIG4 AI 安全论文聚合仓库中的 NDSS 分区。",
        "url": "https://github.com/Zhou-Zi7/Awesome-AI-Security-BIG4",
        "fetcher": "big4_markdown",
        "extra": {"heading": "## Papers in NDSS"},
    },
    {
        "source_id": "usenix",
        "name": "USENIX Security",
        "category": "顶级安全会议",
        "description": "BIG4 AI 安全论文聚合仓库中的 USENIX Security 分区。",
        "url": "https://github.com/Zhou-Zi7/Awesome-AI-Security-BIG4",
        "fetcher": "big4_markdown",
        "extra": {"heading": "## Papers in USENIX Security"},
    },
    {
        "source_id": "ccs",
        "name": "CCS",
        "category": "顶级安全会议",
        "description": "BIG4 AI 安全论文聚合仓库中的 CCS 分区。",
        "url": "https://github.com/Zhou-Zi7/Awesome-AI-Security-BIG4",
        "fetcher": "big4_markdown",
        "extra": {"heading": "## Papers in CCS"},
    },
    {
        "source_id": "icml_2025",
        "name": "ICML 2025",
        "category": "顶级 AI 会议",
        "description": "PMLR ICML 2025 proceedings，按 AI 安全关键词过滤。",
        "url": "https://proceedings.mlr.press/v267/",
        "fetcher": "pmlr_html",
        "extra": {"limit": 80},
    },
    {
        "source_id": "cvpr_2025",
        "name": "CVPR 2025",
        "category": "顶级 AI 会议",
        "description": "CVPR 2025 Open Access 论文页，按计算机视觉安全关键词过滤。",
        "url": "https://openaccess.thecvf.com/CVPR2025?day=all",
        "fetcher": "cvpr_html",
        "extra": {"limit": 80},
    },
    {
        "source_id": "arxiv_llm_security",
        "name": "arXiv · LLM Security",
        "category": "实时论文流",
        "description": "跟踪 LLM security、prompt injection、jailbreak 等方向。",
        "url": "https://arxiv.org/search/?query=llm+security&searchtype=all&abstracts=show&order=-announced_date_first&size=25",
        "fetcher": "arxiv_api",
        "extra": {
            "query": 'all:"llm security" OR all:"prompt injection" OR all:jailbreak OR all:"model backdoor"',
            "limit": 25,
        },
    },
    {
        "source_id": "arxiv_robustness",
        "name": "arXiv · Adversarial Robustness",
        "category": "实时论文流",
        "description": "跟踪 adversarial attack / robustness 相关论文。",
        "url": "https://arxiv.org/search/?query=adversarial+robustness&searchtype=all&abstracts=show&order=-announced_date_first&size=25",
        "fetcher": "arxiv_api",
        "extra": {"query": 'all:"adversarial robustness" OR all:"adversarial attack"', "limit": 25},
    },
    {
        "source_id": "arxiv_poisoning",
        "name": "arXiv · Data Poisoning",
        "category": "实时论文流",
        "description": "跟踪数据投毒、后门攻击和 unlearning 方向。",
        "url": "https://arxiv.org/search/?query=data+poisoning&searchtype=all&abstracts=show&order=-announced_date_first&size=25",
        "fetcher": "arxiv_api",
        "extra": {"query": 'all:"data poisoning" OR all:"backdoor attack" OR all:unlearning', "limit": 25},
    },
    {
        "source_id": "arxiv_privacy",
        "name": "arXiv · Privacy & Inference",
        "category": "实时论文流",
        "description": "跟踪 membership inference、隐私攻击与私有推理。",
        "url": "https://arxiv.org/search/?query=membership+inference&searchtype=all&abstracts=show&order=-announced_date_first&size=25",
        "fetcher": "arxiv_api",
        "extra": {"query": 'all:"membership inference" OR all:"privacy attack" OR all:"private inference"', "limit": 25},
    },
    {
        "source_id": "arxiv_security_of_ai",
        "name": "arXiv · Security of AI",
        "category": "实时论文流",
        "description": "跟踪模型攻击、防御、隐私、越狱、鲁棒性等 Security of AI 方向。",
        "url": "https://arxiv.org/search/?query=security+of+ai&searchtype=all&abstracts=show&order=-announced_date_first&size=25",
        "fetcher": "arxiv_api",
        "extra": {"query": 'all:"security of ai" OR all:"ai security" OR all:"model security" OR all:"llm security"', "limit": 25},
    },
    {
        "source_id": "arxiv_ai_for_security",
        "name": "arXiv · AI for Security",
        "category": "实时论文流",
        "description": "跟踪用 AI 做漏洞挖掘、恶意代码检测、入侵检测等 AI for Security 方向。",
        "url": "https://arxiv.org/search/?query=ai+for+security&searchtype=all&abstracts=show&order=-announced_date_first&size=25",
        "fetcher": "arxiv_api",
        "extra": {
            "query": 'all:"ai for security" OR all:cybersecurity OR all:"intrusion detection" OR all:"malware detection" OR all:"vulnerability detection"',
            "limit": 25,
        },
    },
    {
        "source_id": "anthropic_alignment",
        "name": "Anthropic Research",
        "category": "工业界 Safety / Alignment",
        "description": "Anthropic 官方研究页中与 safety、alignment、interpretability 相关的内容。",
        "url": "https://www.anthropic.com/research",
        "fetcher": "anthropic_html",
        "extra": {"limit": 24},
    },
    {
        "source_id": "deepmind_safety",
        "name": "Google DeepMind Publications",
        "category": "工业界 Safety / Alignment",
        "description": "DeepMind 官方 publications 页中与 AI safety / alignment 高相关的条目。",
        "url": "https://deepmind.google/research/publications/",
        "fetcher": "deepmind_html",
        "extra": {"limit": 24},
    },
]
