CCF_NETWORK_SECURITY_REFERENCE = (
    "根据 CCF《推荐国际学术会议和期刊目录》网络与信息安全方向 A/B 类期刊整理。"
)


SOURCE_DEFINITIONS = [
    {
        "source_id": "tdsc",
        "name": "TDSC",
        "category": "CCF A 类期刊",
        "description": "IEEE Transactions on Dependable and Secure Computing。近 1 年论文。",
        "url": "https://dblp.org/db/journals/tdsc/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "1545-5971",
            "limit": 25,
            "full_name": "IEEE Transactions on Dependable and Secure Computing",
            "publisher": "IEEE",
            "ccf_tier": "A",
        },
    },
    {
        "source_id": "tifs",
        "name": "TIFS",
        "category": "CCF A 类期刊",
        "description": "IEEE Transactions on Information Forensics and Security。近 1 年论文。",
        "url": "https://dblp.org/db/journals/tifs/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "1556-6013",
            "limit": 25,
            "full_name": "IEEE Transactions on Information Forensics and Security",
            "publisher": "IEEE",
            "ccf_tier": "A",
        },
    },
    {
        "source_id": "joc",
        "name": "Journal of Cryptology",
        "category": "CCF A 类期刊",
        "description": "Journal of Cryptology。近 1 年论文。",
        "url": "https://dblp.org/db/journals/joc/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "0933-2790",
            "limit": 25,
            "full_name": "Journal of Cryptology",
            "publisher": "Springer",
            "ccf_tier": "A",
        },
    },
    {
        "source_id": "tops",
        "name": "TOPS",
        "category": "CCF B 类期刊",
        "description": "ACM Transactions on Privacy and Security。近 1 年论文。",
        "url": "https://dblp.org/db/journals/tissec/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "2471-2566",
            "limit": 25,
            "full_name": "ACM Transactions on Privacy and Security",
            "publisher": "ACM",
            "ccf_tier": "B",
        },
    },
    {
        "source_id": "compsec",
        "name": "Computers & Security",
        "category": "CCF B 类期刊",
        "description": "Computers & Security。近 1 年论文。",
        "url": "https://dblp.org/db/journals/compsec/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "0167-4048",
            "limit": 25,
            "full_name": "Computers & Security",
            "publisher": "Elsevier",
            "ccf_tier": "B",
        },
    },
    {
        "source_id": "dcc",
        "name": "DCC",
        "category": "CCF B 类期刊",
        "description": "Designs, Codes and Cryptography。近 1 年论文。",
        "url": "https://dblp.org/db/journals/dcc/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "0925-1022",
            "limit": 25,
            "full_name": "Designs, Codes and Cryptography",
            "publisher": "Springer",
            "ccf_tier": "B",
        },
    },
    {
        "source_id": "jcs",
        "name": "JCS",
        "category": "CCF B 类期刊",
        "description": "Journal of Computer Security。近 1 年论文。",
        "url": "https://dblp.org/db/journals/jcs/index.html",
        "fetcher": "crossref_journal",
        "extra": {
            "issn": "0926-227X",
            "limit": 25,
            "full_name": "Journal of Computer Security",
            "publisher": "IOS Press",
            "ccf_tier": "B",
        },
    },
]
